<!--
  Luminode mark. Generated by tools/brand_assets.py — edit the dial values
  there and re-run rather than tweaking the geometry below.

  Colours come from --mark-ink / --mark-lit / --mark-bg so the mark follows the
  theme; --mark-bg fills the ray terminals and must match whatever surface the
  mark sits on. Geometry steps down with `size`: below 49px the strokes thicken
  and the halo fades, below 25px the halo goes entirely.
-->
<script lang="ts">
  // An empty title marks the instance decorative — use it wherever the
  // wordmark or a heading already names Luminode next to the mark.
  let { size = 28, title = "Luminode" }: { size?: number; title?: string } = $props();
</script>

<svg
  width={size}
  height={size}
  viewBox="0 0 64 64"
  role={title ? "img" : "presentation"}
  aria-label={title || undefined}
  aria-hidden={title ? undefined : "true"}
  class="mark"
>
  {#if size <= 24}
    <line x1="32.00" y1="20.00" x2="32.00" y2="13.80" stroke="var(--mark-ink)" stroke-width="4.2" stroke-linecap="round"/>
    <circle cx="32.00" cy="8.00" r="4.2" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="3.36"/>
    <line x1="42.39" y1="26.00" x2="47.76" y2="22.90" stroke="var(--mark-ink)" stroke-width="4.2" stroke-linecap="round"/>
    <circle cx="52.78" cy="20.00" r="4.2" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="3.36"/>
    <line x1="42.39" y1="38.00" x2="47.76" y2="41.10" stroke="var(--mark-ink)" stroke-width="4.2" stroke-linecap="round"/>
    <circle cx="52.78" cy="44.00" r="4.2" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="3.36"/>
    <line x1="32.00" y1="44.00" x2="32.00" y2="50.20" stroke="var(--mark-ink)" stroke-width="4.2" stroke-linecap="round"/>
    <circle cx="32.00" cy="56.00" r="4.2" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="3.36"/>
    <line x1="21.61" y1="38.00" x2="16.24" y2="41.10" stroke="var(--mark-ink)" stroke-width="4.2" stroke-linecap="round"/>
    <circle cx="11.22" cy="44.00" r="4.2" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="3.36"/>
    <line x1="21.61" y1="26.00" x2="16.24" y2="22.90" stroke="var(--mark-ink)" stroke-width="4.2" stroke-linecap="round"/>
    <circle cx="11.22" cy="20.00" r="4.2" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="3.36"/>
    <circle cx="32" cy="32" r="9" fill="var(--mark-ink)"/>
  {:else if size <= 48}
    <defs><radialGradient id="gm"><stop offset="0%" stop-color="var(--mark-lit)" stop-opacity="0.294"/><stop offset="58%" stop-color="var(--mark-lit)" stop-opacity="0.070"/><stop offset="100%" stop-color="var(--mark-lit)" stop-opacity="0"/></radialGradient></defs>
    <circle cx="32" cy="32" r="17.50" fill="url(#gm)"/>
    <circle cx="32" cy="32" r="10.20" fill="none" stroke="var(--mark-lit)" stroke-width="1.3" opacity="0.52"/>
    <line x1="32.00" y1="20.00" x2="32.00" y2="10.70" stroke="var(--mark-ink)" stroke-width="3.1" stroke-linecap="round"/>
    <circle cx="32.00" cy="5.50" r="3.6" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.48"/>
    <line x1="42.39" y1="26.00" x2="50.45" y2="21.35" stroke="var(--mark-ink)" stroke-width="3.1" stroke-linecap="round"/>
    <circle cx="54.95" cy="18.75" r="3.6" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.48"/>
    <line x1="42.39" y1="38.00" x2="50.45" y2="42.65" stroke="var(--mark-ink)" stroke-width="3.1" stroke-linecap="round"/>
    <circle cx="54.95" cy="45.25" r="3.6" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.48"/>
    <line x1="32.00" y1="44.00" x2="32.00" y2="53.30" stroke="var(--mark-ink)" stroke-width="3.1" stroke-linecap="round"/>
    <circle cx="32.00" cy="58.50" r="3.6" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.48"/>
    <line x1="21.61" y1="38.00" x2="13.55" y2="42.65" stroke="var(--mark-ink)" stroke-width="3.1" stroke-linecap="round"/>
    <circle cx="9.05" cy="45.25" r="3.6" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.48"/>
    <line x1="21.61" y1="26.00" x2="13.55" y2="21.35" stroke="var(--mark-ink)" stroke-width="3.1" stroke-linecap="round"/>
    <circle cx="9.05" cy="18.75" r="3.6" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.48"/>
    <circle cx="32" cy="32" r="6.5" fill="var(--mark-ink)"/>
    <circle cx="32" cy="32" r="2.40" fill="var(--mark-lit)" opacity="0.70"/>
  {:else}
    <defs><radialGradient id="gf"><stop offset="0%" stop-color="var(--mark-lit)" stop-opacity="0.420"/><stop offset="58%" stop-color="var(--mark-lit)" stop-opacity="0.100"/><stop offset="100%" stop-color="var(--mark-lit)" stop-opacity="0"/></radialGradient></defs>
    <circle cx="32" cy="32" r="17.50" fill="url(#gf)"/>
    <circle cx="32" cy="32" r="10.20" fill="none" stroke="var(--mark-lit)" stroke-width="1.3" opacity="0.75"/>
    <line x1="32.00" y1="20.00" x2="32.00" y2="10.20" stroke="var(--mark-ink)" stroke-width="2.6" stroke-linecap="round"/>
    <circle cx="32.00" cy="5.50" r="3.1" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.08"/>
    <line x1="42.39" y1="26.00" x2="50.88" y2="21.10" stroke="var(--mark-ink)" stroke-width="2.6" stroke-linecap="round"/>
    <circle cx="54.95" cy="18.75" r="3.1" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.08"/>
    <line x1="42.39" y1="38.00" x2="50.88" y2="42.90" stroke="var(--mark-ink)" stroke-width="2.6" stroke-linecap="round"/>
    <circle cx="54.95" cy="45.25" r="3.1" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.08"/>
    <line x1="32.00" y1="44.00" x2="32.00" y2="53.80" stroke="var(--mark-ink)" stroke-width="2.6" stroke-linecap="round"/>
    <circle cx="32.00" cy="58.50" r="3.1" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.08"/>
    <line x1="21.61" y1="38.00" x2="13.12" y2="42.90" stroke="var(--mark-ink)" stroke-width="2.6" stroke-linecap="round"/>
    <circle cx="9.05" cy="45.25" r="3.1" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.08"/>
    <line x1="21.61" y1="26.00" x2="13.12" y2="21.10" stroke="var(--mark-ink)" stroke-width="2.6" stroke-linecap="round"/>
    <circle cx="9.05" cy="18.75" r="3.1" fill="var(--mark-bg)" stroke="var(--mark-ink)" stroke-width="2.08"/>
    <circle cx="32" cy="32" r="6.5" fill="var(--mark-ink)"/>
    <circle cx="32" cy="32" r="2.40" fill="var(--mark-lit)" opacity="1.00"/>
  {/if}
</svg>

<style>
  .mark { display: block; flex-shrink: 0; overflow: visible; }
</style>
